# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [120]:
A = np.arange(1, 16).reshape(3,5)

In [122]:
print(A)
print('=============================')

print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [38]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2


print(f'B = \n {B}')
print()
print('======================================')
print()

print(f'C = \n {C}')

print()
print('======================================')
print()

#Calculating the subtraction of B and C
subtraction = B - C
print(f'Elementwise subtraction of B and C (B - C):\n {subtraction}') 

print()
print('======================================')
print()

#Calculating elementwise multiplication of B and C
multiplication = B * C 
print(f'Elementwise multiplication of B and C (B * C):\n {multiplication}')

print()
print('======================================')
print()



print(f'Matrix multiplication:\n {B @ C}')



B = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


C = 
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


Elementwise subtraction of B and C (B - C):
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


Elementwise multiplication of B and C (B * C):
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


Matrix multiplication:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [127]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()

exponentiated_number = np.exp(B)
print(f'Exponentiating each number in the matrix:\n {exponentiated_number}')


print()
print('======================================')
print()

minimum_value_whole = np.min(B)
print(f'Minimum value of the whole matrix: \n{minimum_value_whole}')

print()
print('======================================')
print()


min_each_row = np.min(B, axis=1)
print(f'Minimum value of each row: \n{min_each_row}')

print()
print('======================================')
print()

min_each_col = np.min(B, axis=0)
print(f'Minimum value of each column: \n{min_each_col}')


print()
print('======================================')
print()

min_val_index = np.argmin(B)
print(f'Index of the minimum value in whole matrix: \n{min_val_index}')

print()
print('======================================')
print()

min_val_index_2 = np.argmin(B, axis=1)
print(f'Index of the minimum value in each row: \n {min_val_index_2}')

print()
print('======================================')
print()


sum = np.sum(B)
print(f'Sum of all elements: \n {sum}')

print()
print('======================================')
print()


# Mean of each column(Medelvärde)
mean_each_column = np.mean(B, axis=0)
print(f'Mean of each column: \n {mean_each_column}')

print()
print('======================================')
print()


# Median of each column
median_each_column = np.median(B, axis=0)

print(f'Median for each column: \n {median_each_column}')


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiating each number in the matrix:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


Minimum value of the whole matrix: 
1


Minimum value of each row: 
[1 4 7]


Minimum value of each column: 
[1 2 3]


Index of the minimum value in whole matrix: 
0


Index of the minimum value in each row: 
 [0 0 0]


Sum of all elements: 
 45


Mean of each column: 
 [4. 5. 6.]


Median for each column: 
 [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [98]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [104]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When we provide fewer indices than axes while slicing, it means that we're implicitly selecting all elements along the missing axes.
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 This is a 3x5 matrix, meaning it has 2 dimensions: rows (axis 0) and columns (axis 1).

 This means we're only providing an index for the first axis (the rows), which in this case is 1. The matrix has two axes (rows and columns), but we only specified the row. So, NumPy implicitly assumes we want all elements along the second axis.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [105]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [106]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


To iterate element-wise over a multidimensional NumPy array, we can use the nditer function. 

In [132]:
# We can use nested loops to iterate through each element:
for i in range(A.shape[0]):  # Iterate over rows
    for j in range(A.shape[1]):  # Iterate over columns
        print(A[i, j])  # Access each element
print()
print('==================================================')
# =========================================================================

# or use the nditer method
for j in np.nditer(A):
    print(j)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [113]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


1. a = np.arange(30)
np.arange(30) creates a 1D array with values ranging from 0 to 29 (inclusive). 

2. b = a.reshape((2, 3, -1))
The reshape function is used to reshape the 1D array a into a multidimensional array.

(2, 3, -1) specifies that the reshaped array should have 3 axes (or dimensions).
2: The first axis (or dimension) will have size 2.
3: The second axis will have size 3.
-1: The -1 tells NumPy to automatically determine the size of the third axis based on the total number of elements (30) and the sizes of the other axes.

NumPy needs to figure out the size of the third axis (-1) to ensure the reshaped array still has 30 elements.

Thus, b will be a 3D array with the shape (2, 3, 5).

Interpretation of the 3 axes:
First axis (2): This axis has 2 elements, meaning there are 2 "blocks" or "slices".
Second axis (3): Each block has 3 rows.
Third axis (5): Each row has 5 elements (columns).

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [114]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [115]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [134]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [139]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that the inputs are numpy ndarrays
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray.")
    
    # Validate the operation argument
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'.")

    # Perform addition
    if operation == 'add':
        # Validate that the matrices have the same shape
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same size for addition.")
        return matrix1 + matrix2

    # Perform multiplication
    elif operation == 'multiply':
        # Validate that the matrices can be multiplied
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("The number of columns in the first matrix must equal the number of rows in the second matrix for multiplication.")
        return np.dot(matrix1, matrix2)

# Example
# We have two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Add the matrices
result_add = add_mult_matrices(A, B, 'add')
print("Addition Result:\n", result_add)

# Multiply the matrices
result_multiply = add_mult_matrices(A, B, 'multiply')
print("Multiplication Result:\n", result_multiply)

Addition Result:
 [[ 6  8]
 [10 12]]
Multiplication Result:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [146]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [147]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

With help of the following code can we decide if v2 is a view or copy of v1:

In [151]:
import numpy as np

v1 = np.arange(4)
v2 = v1[-2:]

# Check if v2 is a view of v1
if np.shares_memory(v1, v2):
    print("v2 is a view of v1.")
else:
    print("v2 is a copy of v1.")

v2 is a view of v1.


Basic Indexing Creates a View:

When you use slicing like v1[-2:], it creates a view of the original array (v1).
The view shares the same memory as the original array, so modifying the view affects the original array.
Checking the .base Attribute:

v1.base is None because v1 is the original array.
v2.base points to v1, indicating that v2 is a view of v1.
Modifying the Last Element:

When you modify the last element of v2 (i.e., v2[-1] = 123), the corresponding element in v1 is also modified because they share the same data buffer.
After the modification, v1 becomes [0, 1, 2, 123], and v2 becomes [2, 123].